# Generated by Django 5.2.16 on 2026-07-25 20:40

import apps.prenotazioni.models
import django.contrib.postgres.constraints
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
        ('operatori', '0002_disponibilita'),
        ('servizi', '0001_initial'),
        ('prenotazioni', '0000_btree_gist_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inizio', models.DateTimeField()),
                ('fine', models.DateTimeField()),
                ('stato', models.CharField(choices=[('confermata', 'Confermata'), ('cancellata', 'Cancellata'), ('completata', 'Completata')], default='confermata', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prenotazioni', to='clienti.cliente')),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prenotazioni', to='operatori.operatore')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prenotazioni', to='servizi.servizio')),
            ],
            options={
                'verbose_name': 'Prenotazione',
                'verbose_name_plural': 'Prenotazioni',
                'ordering': ['-inizio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fine__gt', models.F('inizio'))), name='prenotazioni_fine_dopo_inizio'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('stato', 'cancellata'), _negated=True), expressions=[('operatore', '='), (apps.prenotazioni.models.TsTzRange('inizio', 'fine'), '&&')], name='prenotazioni_no_overlap_operatore')],
            },
        ),
    ]
