# Generated by Django 5.2.16 on 2026-07-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='importo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='stato_pagamento',
            field=models.CharField(choices=[('non_pagato', 'Non pagato'), ('pagato', 'Pagato')], default='non_pagato', max_length=20),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='stato_presenza',
            field=models.CharField(choices=[('da_verificare', 'Da verificare'), ('presente', 'Presente'), ('non_presente', 'Non presente')], default='da_verificare', max_length=20),
        ),
    ]
