# Generated by Django 5.2.17 on 2026-09-19 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienti', '0002_cliente_bloccato_cliente_contatore_no_show'),
        ('operatori', '0004_eccezionedisponibilita_creato_il'),
        ('prenotazioni', '0002_prenotazione_importo_prenotazione_stato_pagamento_and_more'),
        ('servizi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaListaAttesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('ora_preferita', models.TimeField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('notificato', 'Notificato'), ('prenotato', 'Prenotato'), ('annullato', 'Annullato')], default='in_attesa', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('notificato_il', models.DateTimeField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste_lista_attesa', to='clienti.cliente')),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richieste_lista_attesa', to='operatori.operatore')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste_lista_attesa', to='servizi.servizio')),
            ],
            options={
                'verbose_name': "Richiesta lista d'attesa",
                'verbose_name_plural': "Richieste lista d'attesa",
                'ordering': ['creato_il'],
            },
        ),
    ]
