# Generated by Django 5.2.17 on 2026-09-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0003_richiestalistaattesa'),
        ('servizi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='servizi_aggiuntivi',
            field=models.ManyToManyField(blank=True, related_name='prenotazioni_secondarie', to='servizi.servizio'),
        ),
    ]
