# Generated by Django 5.2.16 on 2026-07-24 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chiave', models.CharField(help_text='Identificativo del permesso, es. "prenotazioni.crea".', max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Permesso',
                'verbose_name_plural': 'Permessi',
                'ordering': ['chiave'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='roles.permission')),
            ],
            options={
                'verbose_name': 'Ruolo',
                'verbose_name_plural': 'Ruoli',
                'ordering': ['nome'],
            },
        ),
    ]
