# Generated by Django 5.2.16 on 2026-07-25 15:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descrizione', models.TextField(blank=True)),
                ('categoria', models.CharField(help_text='Es. "Taglio", "Colore", "Trattamento", "Barba".', max_length=50)),
                ('durata_minuti', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='servizi/')),
                ('attivo', models.BooleanField(default=True, help_text="Un servizio disattivato non compare piu' nel catalogo cliente.")),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
