# Generated by Django 5.2.17 on 2026-09-19 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_jti', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('dispositivo', models.CharField(blank=True, max_length=150)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('ultimo_accesso', models.DateTimeField(auto_now=True)),
                ('revocata', models.BooleanField(default=False)),
                ('revocata_il', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessione utente',
                'verbose_name_plural': 'Sessioni utente',
                'ordering': ['-ultimo_accesso'],
            },
        ),
    ]
