# Generated by Django 5.2.16 on 2026-07-25 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impostazione',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chiave', models.CharField(max_length=100, unique=True)),
                ('valore', models.CharField(max_length=255)),
                ('descrizione', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Impostazione',
                'verbose_name_plural': 'Impostazioni',
                'ordering': ['chiave'],
            },
        ),
    ]
