# Generated by Django 5.2.17 on 2026-08-18 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('conferma_prenotazione', 'Conferma prenotazione'), ('cancellazione_prenotazione', 'Cancellazione prenotazione'), ('nuova_prenotazione_ricevuta', 'Nuova prenotazione ricevuta'), ('promemoria_prenotazione', 'Promemoria appuntamento'), ('soglia_no_show_raggiunta', 'Soglia no-show raggiunta'), ('cliente_bloccato', 'Cliente bloccato'), ('cliente_sbloccato', 'Cliente sbloccato')], max_length=40)),
                ('titolo', models.CharField(max_length=150)),
                ('messaggio', models.TextField()),
                ('link', models.CharField(blank=True, help_text="Percorso frontend relativo, es. '/le-mie-prenotazioni'.", max_length=255)),
                ('letta', models.BooleanField(default=False)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifica',
                'verbose_name_plural': 'Notifiche',
                'ordering': ['-creato_il'],
            },
        ),
    ]
