# Generated by Django 5.2.17 on 2026-09-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifiche', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifica',
            name='tipo',
            field=models.CharField(choices=[('conferma_prenotazione', 'Conferma prenotazione'), ('cancellazione_prenotazione', 'Cancellazione prenotazione'), ('nuova_prenotazione_ricevuta', 'Nuova prenotazione ricevuta'), ('promemoria_prenotazione', 'Promemoria appuntamento'), ('soglia_no_show_raggiunta', 'Soglia no-show raggiunta'), ('cliente_bloccato', 'Cliente bloccato'), ('cliente_sbloccato', 'Cliente sbloccato'), ('disponibilita_lista_attesa', "Posto disponibile dalla lista d'attesa")], max_length=40),
        ),
    ]
