# Generated by Django 5.2.16 on 2026-07-25 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operatore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('specializzazioni', models.CharField(blank=True, max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='operatori/')),
                ('attivo', models.BooleanField(default=True, help_text="Un operatore non attivo non e' selezionabile per nuove prenotazioni.")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operatore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operatore',
                'verbose_name_plural': 'Operatori',
                'ordering': ['nome'],
            },
        ),
    ]
