# Generated by Django 5.2.16 on 2026-07-25 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('giorno_settimana', models.IntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')])),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilita', to='operatori.operatore')),
            ],
            options={
                'verbose_name': 'Disponibilità',
                'verbose_name_plural': 'Disponibilità',
                'ordering': ['giorno_settimana', 'ora_inizio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ora_fine__gt', models.F('ora_inizio'))), name='disponibilita_ora_fine_dopo_ora_inizio')],
            },
        ),
    ]
