# Generated by Django 5.2.17 on 2026-09-19 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatori', '0002_disponibilita'),
    ]

    operations = [
        migrations.CreateModel(
            name='EccezioneDisponibilita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ferie', 'Ferie'), ('malattia', 'Malattia'), ('permesso', 'Permesso'), ('chiusura', 'Chiusura salone')], default='ferie', max_length=20)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('ora_inizio', models.TimeField(blank=True, null=True)),
                ('ora_fine', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('operatore', models.ForeignKey(blank=True, help_text="Lasciare vuoto se si tratta di una chiusura dell'intero salone.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eccezioni', to='operatori.operatore')),
            ],
            options={
                'verbose_name': 'Eccezione disponibilità',
                'verbose_name_plural': 'Eccezioni disponibilità',
                'ordering': ['-data_inizio', 'ora_inizio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_fine__gte', models.F('data_inizio'))), name='eccezione_data_fine_dopo_data_inizio')],
            },
        ),
    ]
