# Generated by Django 5.2.17 on 2026-09-19 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatori', '0003_eccezionedisponibilita'),
    ]

    operations = [
        migrations.AddField(
            model_name='eccezionedisponibilita',
            name='creato_il',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
