# Generated by Django 5.2.16 on 2026-07-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloccato',
            field=models.BooleanField(default=False, help_text='Blocca nuove prenotazioni da questo cliente (soglia no-show raggiunta).'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contatore_no_show',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
