# Generated by Django 5.2.16 on 2026-07-24 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('azione', models.CharField(max_length=100)),
                ('entita_coinvolta', models.CharField(max_length=100)),
                ('dettagli', models.JSONField(blank=True, default=dict)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voce di audit',
                'verbose_name_plural': 'Log di audit',
                'ordering': ['-creato_il'],
            },
        ),
    ]
